name: Package iOS lib as XCFramework

permissions:
  contents:
    write

on:
  push:
    tags:
      - 'v*'  # publish on tag, e.g. v1.2.3
  workflow_dispatch:  # also allow manual runs
    inputs:
      SQLITE_VERSION:
        type: string
        description: "SQLite version to use"
        required: false
        default: ""

jobs:
  build_framework:
    name: Build Framework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Test library
        run: |
          ( \
          set -o pipefail; \
          xcodebuild test \
            -project sqlite-ios-decimal.xcodeproj \
            -scheme SQLite-Decimal \
            -destination "platform=iOS Simulator,name=iPhone 17 Pro,OS=26.2" \
            -archivePath "./build/SQLite-Decimal-iphoneos.archive" \
            OTHER_CFLAGS="-fembed-bitcode" \
            SYMROOT="./build" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual \
            SQLITE_VERSION="${{ github.event.inputs.SQLITE_VERSION }}" \
            | tee ${{ github.workspace }}/build_iphoneos.log
          )

      - name: Get SQLite version
        id: sqlite_version
        run: |
            SQLITE_VERSION=$(grep -Eo "SQLITE_VERSION=[0-9]+\\.[0-9]+\\.[0-9]+" ${{ github.workspace }}/build_iphoneos.log \
              | grep -Eo "[0-9]+\\.[0-9]+\\.[0-9]+" \
              | head -n1)
            echo "SQLITE_VERSION=$SQLITE_VERSION" >> $GITHUB_OUTPUT

      - name: Create archive for devices (iphoneos)
        run: |
          xcodebuild archive \
            -project sqlite-ios-decimal.xcodeproj \
            -scheme SQLite-Decimal \
            -destination "generic/platform=iOS" \
            -archivePath "./build/SQLite-Decimal-iphoneos" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual \
            SQLITE_VERSION="${{ steps.sqlite_version.outputs.SQLITE_VERSION }}"

      - name: Create archive for simulator (iphonesimulator)
        run: |
          xcodebuild archive \
            -project sqlite-ios-decimal.xcodeproj \
            -scheme SQLite-Decimal \
            -configuration Release \
            -destination "generic/platform=iOS Simulator" \
            -archivePath "./build/SQLite-Decimal-iphonesimulator" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual \
            SQLITE_VERSION="${{ steps.sqlite_version.outputs.SQLITE_VERSION }}"

      - name: Create XCFramework (device + simulator)
        run: |
          xcodebuild -create-xcframework \
            -framework ./build/SQLite-Decimal-iphoneos.xcarchive/Products/Library/Frameworks/SQLite_Decimal.framework \
            -framework ./build/SQLite-Decimal-iphonesimulator.xcarchive/Products/Library/Frameworks/SQLite_Decimal.framework \
            -output ./build/sqlite-ios-decimal.xcframework

      - name: Package XCFramework
        run: |
          mkdir artifacts
          cd build
          zip -r ../artifacts/sqlite-ios-decimal.xcframework.zip sqlite-ios-decimal.xcframework

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: SQLite-Decimal-xcframework
          path: artifacts/sqlite-ios-decimal.xcframework.zip

      - name: Create GitHub Release (optional)
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: SQLite Decimal ${{ github.ref_name }}
          artifacts: artifacts/sqlite-ios-decimal.xcframework.zip

      - name: Create Git tag
        if: github.ref == 'refs/heads/master'
        run: |
          git tag ${{ steps.sqlite_version.outputs.SQLITE_VERSION }}
          git push origin ${{ steps.sqlite_version.outputs.SQLITE_VERSION }}

      - name: Create GitHub release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./artifacts/sqlite-ios-decimal.xcframework.zip
          tag_name: ${{ steps.sqlite_version.outputs.SQLITE_VERSION }}
          name: Release ${{ steps.sqlite_version.outputs.SQLITE_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}